plugins {
	id 'org.springframework.boot' version '4.0.1'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'java'
	id 'jacoco'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '21'


repositories {
	mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    // https://mvnrepository.com/artifact/io.github.resilience4j/resilience4j-spring-boot3
    implementation("io.github.resilience4j:resilience4j-spring-boot3:2.3.0")
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    // force to create proxy class for retry
    implementation "org.aspectj:aspectjweaver:1.9.22"
}

jacoco {
	toolVersion = "0.8.7"
}

jacocoTestReport {
	afterEvaluate {
		classDirectories.setFrom(files(classDirectories.files.collect {
			fileTree(dir: it, exclude: [
					"**/**/EmployeeApplication**"
			])
		}))
	}
}

test {
	useJUnitPlatform()
}
