resilience4j:
  retry:
    retryAspectOrder: 2
    instances:
      restTemplateRetry:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - java.lang.RuntimeException
          - org.springframework.web.client.HttpServerErrorException
          - org.springframework.web.client.ResourceAccessException
  circuitBreaker:
    circuitBreakerAspectOrder: 1
    instances:
      userApiCircuitBreaker:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 20
        minimum-number-of-calls: 15
        permitted-number-of-calls-in-half-open-state: 2
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 50

